<?php

namespace Database\Seeders;

use App\Models\KelompokDetail;
use Illuminate\Database\Seeder;
use App\Models\KelompokDataSektoral;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class JumlahPendudukPerAgama extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kelompokDataSektoral = KelompokDataSektoral::where('kelompok_data','Data Jumlah Penduduk Per Kecamatan menurut Agama  dan Aliran Kepercayaan di Kabupaten Seluma Tahun 2022')->first();
        KelompokDetail::insert([
            [
                'kelompok_data_sektoral_id' =>  $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Sukaraja',
                'islam' => '32524',
                'kristen' => '1356',
                'katolik' => '87',
                'hindu' => '421',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '34388',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma',
                'islam' => '10459',
                'kristen' => '101',
                'katolik' => '16',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '10576',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Talo',
                'islam' => '12560',
                'kristen' => '52',
                'katolik' => '0',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '12612',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Semidang Alas',
                'islam' => '15687',
                'kristen' => '16',
                'katolik' => '0',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '15703',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Semidang Alas Maras',
                'islam' => '25614',
                'kristen' => '35',
                'katolik' => '1',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '25650',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Air Periukan',
                'islam' => '22634',
                'kristen' => '305',
                'katolik' => '29',
                'hindu' => '623',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '23591',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Lubuk Sandi',
                'islam' => '12105',
                'kristen' => '43',
                'katolik' => '3',
                'hindu' => '177',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '12328',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Barat',
                'islam' => '9849',
                'kristen' => '248',
                'katolik' => '46',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '10143',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Timur',
                'islam' => '11155',
                'kristen' => '141',
                'katolik' => '1',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '11297',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Utara',
                'islam' => '9592',
                'kristen' => '10',
                'katolik' => '0',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '9602',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Selatan',
                'islam' => '13832',
                'kristen' => '112',
                'katolik' => '34',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '13978',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Talo Kecil',
                'islam' => '11345',
                'kristen' => '37',
                'katolik' => '0',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '11382',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Ulu Talo',
                'islam' => '6211',
                'kristen' => '39',
                'katolik' => '3',
                'hindu' => '98',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '6351',
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Ilir Talo',
                'islam' => '16558',
                'kristen' => '24',
                'katolik' => '62',
                'hindu' => '0',
                'buddha' => '0',
                'konghucu' => '0',
                'aliran_kepercayaan' => '0',
                'jumlah_penduduk' => '16644',
            ],
        ]);
    }
}
