<?php

namespace Database\Seeders;

use App\Models\KelompokDetail;
use Illuminate\Database\Seeder;
use App\Models\KelompokDataSektoral;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class JumlahPendudukPerGolonganDarah extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kelompokDataSektoral = KelompokDataSektoral::where('kelompok_data','Penduduk Kabupaten Seluma Menurut Golongan Darah Tahun 2022')->first();
        KelompokDetail::insert([
            [
                'kelompok_data_sektoral_id' =>  $kelompokDataSektoral->id,
                'nama_kecamatan'    =>  'Sukaraja',
                'A' => '881',
                'B' => '1029',
                'AB' => '361',
                'O' => '1276',
                'A+' => '15',
                'A-' => '0',
                'B+' => '8',
                'B-' => '0',
                'AB+' => '10',
                'AB-' => '1',
                'O+' => '15',
                'O-' => '24',
                'tidak_tahu'    =>  30768,
                'jumlah'    =>  34388,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma',
                'A' => 469,
                'B' => 252,
                'AB' => 213,
                'O' => 390,
                'A+' => 7,
                'A-' => 1,
                'B+' => 5,
                'B-' => 2,
                'AB+' => 4,
                'AB-' => 0,
                'O+' => 4,
                'O-' => 5,
                'tidak_tahu' => 9224,
                'jumlah' => 10576,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Talo',
                'A' => 180,
                'B' => 138,
                'AB' => 78,
                'O' => 183,
                'A+' => 6,
                'A-' => 0,
                'B+' => 2,
                'B-' => 2,
                'AB+' => 1,
                'AB-' => 7,
                'O+' => 1,
                'O-' => 7,
                'tidak_tahu' => 12014,
                'jumlah' => 12612,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Semidang Alas',
                'A' => 168,
                'B' => 87,
                'AB' => 71,
                'O' => 122,
                'A+' => 4,
                'A-' => 0,
                'B+' => 5,
                'B-' => 1,
                'AB+' => 0,
                'AB-' => 2,
                'O+' => 15,
                'O-' => 15,
                'tidak_tahu' => 15227,
                'jumlah' => 15703,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Semidang Alas Maras',
                'A' => 259,
                'B' => 149,
                'AB' => 109,
                'O' => 216,
                'A+' => 103,
                'A-' => 1,
                'B+' => 61,
                'B-' => 0,
                'AB+' => 43,
                'AB-' => 1,
                'O+' => 97,
                'O-' => 16,
                'tidak_tahu' => 24595,
                'jumlah' => 25650,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Air Periukan',
                'A' => 437,
                'B' => 430,
                'AB' => 181,
                'O' => 504,
                'A+' => 10,
                'A-' => 0,
                'B+' => 5,
                'B-' => 0,
                'AB+' => 0,
                'AB-' => 1,
                'O+' => 8,
                'O-' => 11,
                'tidak_tahu' => 22004,
                'jumlah' => 23591,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Lubuk Sandi',
                'A' => 322,
                'B' => 219,
                'AB' => 107,
                'O' => 263,
                'A+' => 1,
                'A-' => 0,
                'B+' => 2,
                'B-' => 2,
                'AB+' => 4,
                'AB-' => 0,
                'O+' => 2,
                'O-' => 8,
                'tidak_tahu' => 11398,
                'jumlah' => 12328,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Barat',
                'A' => 243,
                'B' => 179,
                'AB' => 84,
                'O' => 216,
                'A+' => 24,
                'A-' => 2,
                'B+' => 11,
                'B-' => 0,
                'AB+' => 7,
                'AB-' => 1,
                'O+' => 15,
                'O-' => 12,
                'tidak_tahu' => 9349,
                'jumlah' => 10143,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Timur',
                'A' => 167,
                'B' => 113,
                'AB' => 58,
                'O' => 161,
                'A+' => 17,
                'A-' => 0,
                'B+' => 8,
                'B-' => 0,
                'AB+' => 6,
                'AB-' => 1,
                'O+' => 12,
                'O-' => 5,
                'tidak_tahu' => 10749,
                'jumlah' => 11297,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Utara',
                'A' => 68,
                'B' => 22,
                'AB' => 25,
                'O' => 55,
                'A+' => 1,
                'A-' => 0,
                'B+' => 1,
                'B-' => 0,
                'AB+' => 1,
                'AB-' => 5,
                'O+' => 9,
                'O-' => 602,
                'tidak_tahu' => 9424,
                'jumlah' => 9602,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Seluma Selatan',
                'A' => 192,
                'B' => 153,
                'AB' => 96,
                'O' => 256,
                'A+' => 70,
                'A-' => 1,
                'B+' => 26,
                'B-' => 1,
                'AB+' => 22,
                'AB-' => 0,
                'O+' => 64,
                'O-' => 6,
                'tidak_tahu' => 13091,
                'jumlah' => 13978,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Talo Kecil',
                'A' => 425,
                'B' => 278,
                'AB' => 214,
                'O' => 235,
                'A+' => 7,
                'A-' => 2,
                'B+' => 6,
                'B-' => 6,
                'AB+' => 8,
                'AB-' => 1,
                'O+' => 7,
                'O-' => 7,
                'tidak_tahu' => 10186,
                'jumlah' => 11382,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Ulu Talo',
                'A' => 39,
                'B' => 37,
                'AB' => 27,
                'O' => 57,
                'A+' => 7,
                'A-' => 0,
                'B+' => 11,
                'B-' => 0,
                'AB+' => 7,
                'AB-' => 1,
                'O+' => 16,
                'O-' => 5,
                'tidak_tahu' => 6144,
                'jumlah' => 6351,
            ],
            [
                'kelompok_data_sektoral_id' => $kelompokDataSektoral->id,
                'nama_kecamatan' => 'Ilir Talo',
                'A' => 108,
                'B' => 67,
                'AB' => 44,
                'O' => 134,
                'A+' => 16,
                'A-' => 0,
                'B+' => 14,
                'B-' => 1,
                'AB+' => 4,
                'AB-' => 10,
                'O+' => 13,
                'O-' => 16,
                'tidak_tahu' => 16233,
                'jumlah' => 16644,
            ],
        ]);
    }
}
